/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer.gltf --types 
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-f844c0357d284fd8baa1435e9ff31bb2
Title: Retro computer
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { AnimationAction } from "three";

type GLTFAction = Record<string, AnimationAction>;

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
  }
  materials: {
    Part2: THREE.MeshStandardMaterial
    Part1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('/desktop pc/computer.gltf') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Part2}>
            <meshStandardMaterial {...materials.Part2}
              side={THREE.FrontSide}
              transparent={false}
              opacity={1}
              alphaMap={null}
              depthWrite={true}
            />
          </mesh>

          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Part1}>
            <meshStandardMaterial {...materials.Part1}
              side={THREE.FrontSide}
              transparent={false}
              opacity={1}
              alphaMap={null}
              depthWrite={true}
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.gltf')
